apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: monitoring-dev
  namespace: fleet-local
spec:
  repo: https://github.com/dlawton20-devops/gitops
  branch: main
  paths:
    - monitoring
  targets:
    - name: dev-clusters
      clusterSelector:
        matchLabels:
          env: dev
