apiVersion: v2
name: monitoring-stack
description: Monitoring stack with Prometheus, Grafana, and Alertmanager
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: kube-prometheus-stack
    version: 55.5.0
    repository: oci://harbor.your-domain.com/monitoring 