apiVersion: fleet.cattle.io/v1alpha1
kind: Bundle
metadata:
  name: monitoring
  namespace: monitoring
spec:
  helm:
    chart: kube-prometheus-stack
    version: "55.5.0"
    repo: https://prometheus-community.github.io/helm-charts
    values:
      grafana:
        enabled: true
        adminPassword: "changeme"
      prometheus:
        enabled: true
      alertmanager:
        enabled: true
