apiVersion: fleet.cattle.io/v1alpha1
kind: Bundle
metadata:
  name: monitoring
  namespace: fleet-local
spec:
  resources:
  - content: |
      apiVersion: v1
      kind: Namespace
      metadata:
        name: monitoring
        labels:
          name: monitoring
    name: namespace.yaml
  - content: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: nginx-test
        namespace: monitoring
        labels:
          app: nginx-test
      spec:
        replicas: 1
        selector:
          matchLabels:
            app: nginx-test
        template:
          metadata:
            labels:
              app: nginx-test
          spec:
            containers:
            - name: nginx
              image: nginx:latest
              ports:
              - containerPort: 80
    name: nginx-deployment.yaml
  targets:
  - clusterSelector:
      matchLabels:
        env: dev
    defaultNamespace: monitoring
